// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqmqcvugwnwuqgbbkyhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxbXFjdnVnd253dXFnYmJreWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDYyMjksImV4cCI6MjA2MjE4MjIyOX0.T0bZ1O_13xRMiF2yvTABfT94k4fdZxjfNn-Eo3KmCWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);